change-inventory: true # 게임모드가 바뀔 때 인벤토리를 따로 둘지 여부를 설정합니다.

permission-message: "당신은 이 명령어를 사용할 권한이 없습니다. 만약 자신이 관리자임을 믿는다면, /su <관리자키> 로 관리자임을 입증해주세요."

allow-sell-command: false # /판매 명령어를 크리에이티브 모드에서 사용할 수 있을지에 대한 여부를 결정합니다.

allow-drop-item: false # 게임모드일 경우 아이템 드롭을 혀용할 지에 대한 여부를 결정합니다.